### ISSUE TITLE
Didn't See It Mentioned, Power Pole Lights Cause HUGE FPS Drop When Lights Are On

### ISSUE THREAD

**Issue by DizzyDJW** [Panakotta00/LightItUp#13]
Not much else to say, title explains the issue.
No fps issue when lights are off, and HUGE drop in fps when lights turn on and are within *range.

*i.e. able to see the areas lit by the light

**Comment by ClassyCircuit** [comment]
Yes, I have exactly the same problem.
We don't even need to place many power poles, 3 or 4 are enough to drop the FPS by 50%.
I have RTX 2060S GPU which can run Satisfactory on Ultra settings at stable 60 FPS under any conditions, but when these power poles are enabled then FPS drops to 20 - 30 FPS.

Performance impact is enormous and should be investigated.

@Panakotta00 
**In Unreal Engine 4 it is possible to reduce shadow casters for objects with dynamic light, they must be limited otherwise it is a performance killer. You can have thousands of directional lights, but there must be only a handful of shadow casters.**

I don't know if you can modify this with a mod, or must be done in the game itself, but until this issue is solved the mod is unusuable.

**Comment by Panakotta00** [comment]
The problem is just if I disable shadows completely which would cause the lamps to shine through the ceiling.
Not ideal.
I'm trying out some tweaks so I hope this solves it.
The weird thing is though... many people don't have that huge problems as long as you don't place the lamps to close to each other.
